[FIX] l10n_nl: Add the condition for tag
While upgrading to version 16.0, an error occurs due to this file. The tag
'3bl (omzet)' is not present in version 16.0, so it return False value and this
 False value being updated in this query and 'account_account_tag_id' is an
integer type and  'old_tax_tags' a boolean value

```
2024-07-01 15:37:54,561 28 ERROR db_1780619 odoo.sql_db: bad query:
                UPDATE account_account_tag_account_tax_repartition_line_rel
                SET account_account_tag_id = 150
                WHERE account_tax_repartition_line_id = ANY(ARRAY[1831,1832])
                AND account_account_tag_id = false

ERROR: operator does not exist: integer = boolean
LINE 5:                 AND account_account_tag_id = false
                                                   ^
HINT:  No operator matches the given name and argument types. You might need to
add explicit type casts.
```

closes odoo/odoo#171577

Signed-off-by: Aliya Tastemirova (alta) <alta@odoo.com>