[FIX] base: fix incorrect call of method of dictionary
This PR fixes an issue introduced in commit https://github.com/odoo/odoo/commit/b9feebc25cc8caad97e5c3cb2953643bfd14984f

When this line is executed, the following error is shown:

closes odoo/odoo#108609

Attributeerror: 'dict' object has no attribute 'vals'
Signed-off-by: Xavier Morel (xmo) <xmo@odoo.com>