[FIX] l10n_cl: added a constraint for latam document number
An error currently occurs when a user tries to confirm an account move using a
document number that isn’t purely numeric and contains ASCII characters other
than digits.

Steps to replicate:
- Install `l10n_cl` with demo and switch to CL company.
- Create a new invoice and add customer as `Andes Innovación SpA`.
- Add a move line > Add a product, price and tax.
- Give Document Number as `11-11`.
- Save and Confirm.

Error:
```
  File /home/odoo/odoo18/enterprise/account_accountant/models/account_move.py, line 119, in action_post
    res = super().action_post()
  File /home/odoo/odoo18/community/addons/account/models/account_move.py, line 5478, in action_post
    self._post(soft=False)
  File /home/odoo/odoo18/enterprise/l10n_cl_edi/models/account_move.py, line 161, in _post
    move._l10n_cl_create_dte()
  File /home/odoo/odoo18/enterprise/l10n_cl_edi/models/account_move.py, line 646, in _l10n_cl_create_dte
    folio = int(self.l10n_latam_document_number)
ValueError: invalid literal for int() with base 10: '11-11'
```

Cause:
- Trying to convert the document number to integer which includes some
  characters that are not numeric causes the error.

Solution:
- Specifically for Chile, the document number (folio) cant include anything
  other than numbers (Check the Sources listed below).
- Added a constraint on the field `l10n_latam_document_number` which only allows
  numbers using regex.

Sources:
- https://www.sii.cl/pagina/clave/folio.htm : The official Internal Revenue
  Service website for Chile provides information on the standard folio, along
  with a sample.
- https://www.sii.cl/factura_electronica/formato_dte.pdf : Refer to PG:11,
  Sr No:3, which specifies that the Folio should be of type NUM, meaning it
  must contain only numeric characters.
- The folio is created [here] that will be sent later to the authorities in the
  form of xml.

[here]: https://github.com/odoo/enterprise/blob/5a8bdb586e2d0bf9948a2d0b4c5e30b3849c0414/l10n_cl_edi/template/dte_template.xml#L8

No ID

closes odoo/odoo#241505

Signed-off-by: Olivier Colson (oco) <oco@odoo.com>