[FIX] survey: fix traceback when viewing question's options
Currently, you cannot view a survey question's option through the
'Questions and Answers' menu.

Steps to reproduce
------------------
* install and open 'survey'
* access all survey questions from the menu 'Questions and Answers' >
  'Questions'
* open any question and try to view the 'Options' tab

You will be met with the following traceback:
```
EvalError: Can not evaluate python expression: ({'referenceValue': parent.session\_speed\_rating})
Error: Name 'parent' is not defined
```

Cause
-----
'parent' here refers to a survey container record and works only inside
sub-views of relational fields.

opw-5026204

closes odoo/odoo#225840

Signed-off-by: Florian Charlier (flch) <flch@odoo.com>