[FIX] stock: fix stock.traceability.report XML-RPC method call
Trying to call the get_lines() method of the stock.traceability.report
model was failing using the external API, due to the response containing
None values. Making sure that False is returned instead of None fixes
this.

The XML-RPC client error is the following:

closes odoo/odoo#147831

Typeerror: cannot marshal None unless allow_none is enabled
Signed-off-by: William Henrotin (whe) <whe@odoo.com>