[FIX] l10n_in_ewaybill_stock:  LazyGettext traceback and missing response
backport of https://github.com/odoo/odoo/commit/b7b987c4077c064fdfdb6b956379455cbdd93de3
on generating ewaybill through irn following traceback is produced

```
File "/home/odoo/src/odoo/addons/l10n_in_ewaybill_stock/tools/ewaybill_api.py", line 165, in _ewaybill_generate

return self._ewaybill_make_transaction("generate", json_payload)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/odoo/src/odoo/addons/l10n_in_ewaybill_stock/tools/ewaybill_api.py", line 157, in _ewaybill_make_transaction

response = self._ewaybill_get_by_consigner(

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/odoo/src/odoo/addons/l10n_in_ewaybill_stock/tools/ewaybill_api.py", line 181, in _ewaybill_get_by_consigner

'message': self.DEFAULT_HELP_MESSAGE % 'generated',

~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

TypeError: unsupported operand type(s) for %: 'LazyGettext' and 'str'
```

In this commit we resolve this issue
opw-5079789

closes odoo/odoo#226622

Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>