[FIX] l10n_es_edi_tbai: traceback on invoice process
Open tax "IVA 0% Entregas Intracomunitarias exentas"
Set Tax Scope to False
Create an invoice to an EU partner
Add an invoice line (select the mentioned tax)
Confirm
Send for Validation

Traceback:
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'DesgloseTipoOperacion'
Template: l10n_es_edi_tbai.template_invoice_factura
Path: /t/TipoDesglose/DesgloseTipoOperacion/PrestacionServicios
Node: <PrestacionServicios t-if="invoice_info.get(\'PrestacionServicios\')"/>

This occurs because tax info was not fetched properly
When invoicing to a foreign partner the tax scope needs to be properly
configured

opw-3877924

closes odoo/odoo#171018

Signed-off-by: Josse Colpaert <jco@odoo.com>