[FIX] sale: Allow users to edit discount custom field
Steps:
	- Install `sale_management` and `web_studio`
	- Open a form view that doesn't contains `order_line`
	for example `helpdesk`'s form view
	- Open studio in this form view and add a many2many `Sales order`
	- Close Studio
	- Open an existing record and click on the first record in the `m2m`
	- Try to edit `discount` field
	- Traceback

```js
UncaughtClientError > TypeError
Uncaught Javascript Error > Cannot read properties of undefined (reading 'records')
TypeError: Cannot read properties of undefined (reading 'records')
at ProductDiscountField.onChange
```

This traceback comes from the fact that `ProductDiscountField` assume
that the parent model necessarily contains a field called `order_line`
in the `onChange` method.

https://github.com/odoo/odoo/blob/fb8b217f8bd2323d33bbeb949f35cd1620557960/addons/sale/static/src/js/product_discount_field.js#L23-L27

This is not the case here, since the field name is `x_studio_*`

This commit corrects this by checking that the parent model actually
contains an `order_line` and return if not

opw-3627398

closes odoo/odoo#155344

Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>