[REV] tools: revert #171722 and #172789: base: stdnum library timeout
This reverts commit 561d67311273423f893198c486741c2c03b5046b.
This reverts commit 9d184b7de626c9ee2c980fb5f9d05816417fd4f6.

The first PR (#171722) caused a dependency problem as `zeep` starts to
use the `platformdirs` package, which may not be installed because e.g.
on Ubuntu 22.04 it is not a dependency of the `zeep` package, for
some reason.

The second PR builds upon that, and is reverted at the same time, so we
can make a clean commit.

The symptom is a traceback as soon as any zeep CachingClient is created,
on impacted systems:
```
File "odoo/tools/_monkeypatches.py", line 97, in new_get_soap_client
client = CachingClient(wsdlurl, transport=transport).service
File "/usr/lib/python3/dist-packages/zeep/client.py", line 255, in __init__
from zeep.cache import SqliteCache
File "/usr/lib/python3/dist-packages/zeep/cache.py", line 10, in <module>
import platformdirs
ModuleNotFoundError: No module named 'platformdirs'
```

The original implementation inside `stdnum` wasn't failing in this case
because it did fallback to non-caching clients in case of ImportError:
https://github.com/arthurdejong/python-stdnum/blob/e951daca447f678f5a3f3c70dcc535eb8d7449b4/stdnum/util.py#L247-L285