[FIX] stock_landed_cost: use invoice date currency exchange
Fixes an issue where the landed cost computation was based on the exchange rate of the accounting date instead of the invoice date, causing discrepancies in valuation and vendor bill. Now, the exchange rate of the invoice date is correctly utilized for accurate landed cost calculation.

To reproduce the issue:

1. Create a purchase order
2. Receive the product
3. Create a vendor bill for landed cost product in a different currency
4. Click on the "Create Landed Cost" button in the vendor bill

Error: The landed cost is computed using the exchange rate of the accounting date, while the total on the invoice is calculated using the invoice date's exchange rate. This results in a discrepancy between the bill price and the valuation.

The fix ensures that the exchange rate of the invoice date is used for computing the total for the landed cost.

opw-3862915

closes odoo/odoo#165155

Signed-off-by: William Henrotin (whe) <whe@odoo.com>