[FIX] l10n_sa_edi: Hide ZATCA fields if not allowed to access
Steps to reproduce
------------------
1. Install the `l10n_sa_edi` module.
2. Create a user X with `Advisor` as Accounting Rights only
3. Log in as user X and try accessing a sales Journal for company SA

Issue
-----
Error: Rendering Failed

Cause
-----
When a user without the group `base.group_system` tries to access the
`l10n_sa_compliance_csid_json` or `l10n_sa_production_csid_json` fields
(needed to display the ZATCA process steps) in the journal form view,
the rendering fails.

Solution
--------
Hide the ZATCA process steps if the user does not have access to
`l10n_sa_compliance_csid_json` or `l10n_sa_production_csid_json` fields.

opw-3812234

closes odoo/odoo#163572

X-original-commit: 6f5f4f21dcfe2cb5297f01bdbaaca23cf738f042
Signed-off-by: Brice Bartoletti (bib) <bib@odoo.com>
Signed-off-by: Nasreddin Boulif (bon) <bon@odoo.com>