[FIX] stock_account: Correctly pass ID rather than record
When trying to prepare account move line, we are unexpectedly browsing a record instead of the record's ID. This causes
psycopg2.ProgrammingError: can't adapt type 'stock.valuation.layer'

Step to reproduce:

1. Set up product

	storable
	Average cost
	Automated Inventory Valuation
	set a standard price e.g $27
2. Create a purchase order for 1 unit in another currency E.g Eur

3. Confirm the purchase order and validate the transfer.

4. Go on the transfer and create a return. Change the return quantity to be more than what received E.g 100

5. Process the return.

6. Go back to the purchase order and create a vendor bill

7. Now try to create a new purchase order and receive the item.

Fix:

pass in vacuum_svl.id instead of just vacuum_svl into _prepare_account_move_line

opw-3555146

closes odoo/odoo#139531

Signed-off-by: William Henrotin (whe) <whe@odoo.com>