[FIX] website_sale: add product with extra price to cart
Version: 16.0

Prerequisites:
- "Pricelist" enabled
- "Prevent Sale of Zero Priced Product" enabled

Steps:
- Create a product:
	- Sales Price: 0
	- In the  "Sales" tab set "website" to a website
	- Add Extra Prices (smart button)
		- Public Pricelist (USD)
		- Min. Quantity: 0
		- Price: 100
- Go to the shop, choose the correct pricelist and try to add the product to the cart

Issue:
UserError:  The given product does not have a price therefore it cannot be added to cart.

Cause:
It doesn't compare the good price list considering the context

opw-3339524

closes odoo/odoo#124805

Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>