[FIX] website_slides: prevent exception while accessing embed external of slide
Currently, an exception is generated when the user tries to access embed view
of slides by following the steps:
 - Install "eLearning" with a demo data
 - Open external embed view of slide 1 by "/slides/embed_external/1" in url

Error:
`AttributeError: 'slide.channel' object has no attribute 'website_share_url'`

This error is because commit [1] added code that tries to access the
'website_share_url' field in the 'slide.channel' model in template
'embed_slide' , but it actually belongs to 'slide.slide'.

This commit resolved the above issue by accessing "website_share_url"
with "slide" instead of "slide.channel".

[1]-https://github.com/odoo/odoo/commit/db63c03af9932ae4d9b786620e88e62ce938589a

sentry-5095823727

closes odoo/odoo#159238

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>