[FIX] stock: apply putaway on package with one product category
When applying the putaway rules, if we redirect a package (with a
specific type), we don't check the category of the package products.

To reproduce the issue:
1. In Settings, enable
   - Packages
   - Multi-Step Routes
   - Storage Categories
2. Edit the warehouse:
   - Receipt: 2 steps
3. Create three categories C1, C2, C3
   - Parent: All
4. Create three locations L1, L2, L3
   - Parent: WH/Stock
5. For each location Lx, create a putaway rules PRx:
   - From: WH/Stock
   - Category: Cx
   - To: Lx
6. Create a product P
   - Type: Storable
   - Category: C2
7. Create a planned receipt R with 1 x P
8. Mark it as todo, set the done quantity and put it in pack
9. Set a type on the package
10. Mark R as done
11. Open the associated internal transfer

Error: the destination location of the package is not L2 -> an
incorrect putaway rule has been applied

When we try to apply the PR on the SML "input to stock", because
this is a package with a type, we don't provide the list of the
products. Therefore, we have no idea about the product category.
This is a shame in case of a package that contains some products of
the same category. We should be able to apply the putaway rules
related to that category.

Moreover, this commit also fixes two other issues explained in [1]
and [2]. The FW of these commits have been stopped for the current
one because they didn't fix the above use case. Moreover, this commit
simplifies/clarifies the filtering and sorting of all putaway rules

[1] 03e47b165e7f6c59b41509d9229e8e2074aa3f34
[2] e0098eb281d886797a888a6f8fac474bbacb1b09

OPW-3098452

Part-of: odoo/odoo#109570