[FIX] crm: allow lead creation with partner without email
Issue:
When trying to create a lead for a partner that has no email. It raises an error that the email is null.
This happens because the code expects 'emails' to contain email_from, even though it could just be email_cc in there.

Steps to reproduce:
1- Install CRM app.
2- Enable leads in CRM settings
3- In sales menue choose customers
4- Create a new customer without providing an email
5- Choose Leads
6- Create a new lead using the newely created customer
7- You get "AttributeError: 'bool' object has no attribute 'lower'" in line: https://github.com/odoo/odoo/blob/8e17a4d76bbdd547536e62ee12a2c514a16d1700/addons/crm/models/crm_lead.py#L1873

Solution:
The main issue is the code relies on the email to provide a name for the lead, so we need to check if there's an email provided beforehand

opw-3681485

closes odoo/odoo#154061

X-original-commit: 3d444247e5b7d65c5e58311cbc005e0f0d4dbbef
Signed-off-by: Omar Abosamaha (abom) <abom@odoo.com>
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>