[FIX] sale: make payment when journal type is not sale
This traceback arises when a user tries to make a payment on the website.

To reproduce this issue:

1) Install 'website_sale'
2) open invoicing/configuration/journals
3) Change the journal type if it is 'sales'
4) Install and enable 'Wire Transfer' payment provider in
   invocing/configuration/Payment Providers
5) Now open 'website/shop' add any product to cart and proceed to checkout
6) Make a payment with 'Wire Transfer'

Error: 'ValueError Expected singleton: account.journal()'

On '_compute_sale_order_reference' method, 'invoice_journal' variable
is getting values with the reference of 'type=sale'.
See:-
https://github.com/odoo/odoo/blob/ebc4ed6c4fb11b01be28cf417b27de83d5361cef/addons/sale/models/payment_transaction.py#L20-L30

Because of user changed the type of journal, 'invoice_journal'
value will be empty recordset and it is referenced to call
'_process_reference_for_sale_order' method.

In '_process_reference_for_sale_order' method ensure_one() is used,
which leads to above traceback.

sentry-4392496618

closes odoo/odoo#131934

Signed-off-by: Olivier Colson (oco) <oco@odoo.com>