[FIX] web: fix back button error in barcode dialog
Steps to reproduce:
1. Install `barcode`
2. Barcode > 'click to scan'
3. Before the camera preview loads, click the back button of the dialog or 'Esc'

Issue:
A traceback occurs:
OwlError: The following error occurred in onMounted:
'Cannot set properties of null (setting 'srcObject')'

Cause:
Clicking the back button triggers `onWillUnmount`, which clears the stream
and sets `this.videoPreviewRef.el` to null. However, some asynchronous
functions in `onMounted` are still pending and try to access the video
element, leading to a crash.

Solution:
Add a safe check based on component status before accessing `this.videoPreviewRef.el`

opw-5055566

closes odoo/odoo#229937

X-original-commit: 7a7c6ffaba20062b88f5b1b520c2f07698cd02b5
Signed-off-by: Romeo Fragomeli (rfr) <rfr@odoo.com>