[FIX] account: access error on payment register
- Activate Factur-x in the customer invoices journal
- Login with a user having no 'Administration' access rights
- Create an invoice to a customer without zip code
- Confirm the invoice > The xml in the EDI Documents is not sent (State: To Send)
- Register a payment > Create payment

Error: Sorry, you are not allowed to access this document.
This occurs because the system attempt to unlink the invoice factur-x
attachment

opw-3784230

closes odoo/odoo#157894

X-original-commit: aeefffc5d1fd5d04db7f352d24e2125cccd58ecd
Signed-off-by: Laurent Smet (las) <las@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>